afes-website/docs

swagger.yaml

運営者ログインシステムの追加

---

swagger.yaml

#20 article/updateに400と409のエラーレスポンスを追加

---

swagger.yaml

必要ないプロパティを削除しようとしたらもはや別物だったので、スキーマとか作らないでやった

#21 requiredが多すぎた問題の解消

---

swagger.yaml

#36: 検索クエリ

---

swagger.yaml

関連issue: #34 
前回の #39 からの変更点
CRを解消した
revisionにも対応した

#34 authorを返すようにする

---

swagger.yaml

regex書いただけ Swagger Editorだとjson直接編集だからvalidateかからないけど、まあ

#37: ブログ記事path制限

---

README.md

#42: READMEを書いた

---

README.md

readme badge

---

swagger.yaml

ogimageをかいた

---

swagger.yaml

カテゴリーを返すAPIを追加

---

swagger.yaml

#62 ハンドルネームのプロパティを追加した

---

swagger.yaml

#68 blog revision の status は readOnly であるべき

---

swagger.yaml

swaggerの内容が固まったので1.7.0にバージョンを上げておく

update to 1.7.0

---

swagger.yaml

#81 管理系アプリ

---

swagger.yaml

#83 reservationIDを返すように修正

---

swagger.yaml

#88 reservationObjectにIDを含めた

---

swagger.yaml

#90 #82で指摘されなかったレビューを諸々修正

---

package.json
yarn.lock

close #96 
なんか調べながらやったら front と別な感じになってしまいました
@ibuki2003 なんか不味いとかおかしいとかあったら教えて

#96 pre commit lint

---

package.json

#102 rename package

---

src/apis/blog/articles/@types.ts
src/apis/blog/revisions/@types.ts

close #107 
before commit で build すべき(???)

#107 import ぶっ壊れ事件 修正

---

package.json
yarn.lock

#106 aspida アプデ

---

src/apis/general/term/index.ts

term情報をgetした

---

src/apis/blog/articles/@types.ts
src/apis/blog/revisions/@types.ts
src/apis/blog/revisions/index.ts

fix #125 
`BlogRevision`, `BlogArticle` を直しました

#125 API 定義を正確に

---

package.json

release v2.2.0

---

package.json

Release v2.2.1

---

.github/workflows/publish.yml
package.json

close #135 
ちょっと自信ないですがまあ動かしてみればわかる
TOKEN は secrets に登録済み

#135 package として公開

---

src/apis/online/exhibition/drafts/@types.ts

#138 created_at を draftCommentに

---

package.json

Release v2.2.2

---

.github/workflows/publish.yml
package.json

#140 workflow を直した

---

src/apis/online/exhibition/drafts/@types.ts

#144 add author in draft

---

src/apis/online/exhibition/drafts/_id@number/index.ts
src/apis/online/exhibition/drafts/index.ts

#148 draft

---

src/apis/online/exhibition/drafts/@types.ts
src/apis/online/exhibition/drafts/index.ts

#148 奇妙な403

---

src/apis/online/drafts/@types.ts
src/apis/online/drafts/_id@number/accept/index.ts
src/apis/online/drafts/_id@number/comment/index.ts
src/apis/online/drafts/_id@number/index.ts
src/apis/online/drafts/_id@number/publish/index.ts
src/apis/online/drafts/_id@number/reject/index.ts
src/apis/online/drafts/index.ts
src/index.ts

close #152 
_id@string と相性が悪いので移動

#152 /online/exhibition/drafts -> /online/drafts

---

package.json

Release v2.2.5

---

src/apis/images/_id@string/@types.ts
src/apis/images/_id@string/index.ts

fix #157 
```ts
resBody: File
```
であってるのかちょっと自信がない

#157 image/_id パスを追加

---

src/apis/online/drafts/@types.ts

#156 DraftParameter を直した

---

package.json

#155 prepare script を消した

---

package.json

Release v2.2.6

---

package.json
src/apis/images/_id@string/@types.ts

#162 image query type - Release v2.2.7

---

package.json
src/apis/online/drafts/@types.ts

fix #164 
実質的に back の実装に寄せる形になりますが、間違えるくらいややこしいならほかとの統一を図りましょう

#164 DraftComment.comment -> content | Release v2.2.8

---

src/apis/online/exhibition/@types.ts

close #168 
まだ展示物がありません……… とかそんな感じ（そもそも list に出さないべきかもね）

#168 Exhibition.content を null-able にしたよ

---

src/apis/online/exhibition/@types.ts
src/apis/online/exhibition/index.ts

#170 
運用としては、フロ局に `blogAdmin` 渡して、id 指定で更新してもらうとかじゃないかなぁ

#170 フロンティア・ステージ展示対応

---

src/apis/online/exhibition/@types.ts
src/apis/online/exhibition/_id@string/index.ts
src/apis/online/exhibition/index.ts

close #166 
実質的な DB 操作なので、`admin` permission が良さそう

#166 exhibition $post / $patch

---

package.json

Release v2.2.9

---

LICENSE
package.json

close #184
- docs: add LICENSE
- docs: add license to package.json

#184 add MIT LICENSE

---

src/apis/onsite/exhibition/enter/index.ts
src/apis/onsite/exhibition/exit/index.ts
src/apis/onsite/general/enter/index.ts
src/apis/onsite/reservation/_id@string/check/index.ts

#187 check pathを生成

---

package.json
src/apis/onsite/reservation/_id@string/check/index.ts

resolve: #190
- feature: give resevation to get reserv/check
- update 2.2.15

#190 reserv/check の権限拡張

---

package.json
src/apis/onsite/reservation/_id@string/check/index.ts

fix: #192
- fix: make reservation/check/status_code nullable
- update v2.2.17

#192 status_codeをnullableにした

---

package.json
src/apis/onsite/exhibition/status/@types.ts

#196 termの条件を追記

---

src/apis/onsite/exhibition/status/_id@string/index.ts
src/apis/onsite/exhibition/status/index.ts

resolve: #198
- feat: allow general to get exh/_id
- feat: allow exh to get exh/status/show

#198 exh/generalが(他の)展示情報を見れるように

---

package.json
src/apis/onsite/general/term/@types.ts

close #206
- feat: rename GuestIdPrefix -> GuestType
- feat: replace prefix with guest type id

#206 GuestIdPrefix を GuestType に変更 [v2.2.21]

---

.github/workflows/publish.yml
package.json

yaml syntax で怒られてた…（気づかなかった…）
- fix: specify conditional expressions
- fix: replace === -> ==
- v2.3.0-alpha.1

fix yaml syntax

---

package.json
src/apis/onsite/general/guest/_id@string/log/@types.ts

close #220
- feat: replace enum with string literal union
- v2.3.0-alpha.3

#220 enum を string literal union で置き換えた

---

package.json
src/index.ts

#199-2 export ファイルの修正

---

.eslintrc.js
.github/workflows/test_pull_request.yml
.prettierignore
.prettierrc.js
package.json
yarn.lock

close #225
- build: upgrade typescript to v4.2.3
- build: upgrade aspida to v1.6.3
- build: upgrade eslint, prettier, and others
- lint: renew lint config
- ci: create test pull request
- v2.3.0-alpha.6

#225 update packages and pr test

---

package.json
src/apis/onsite/exhibition/status/@types.ts

resolve: #223
- feat: name and thumbnail_image_id in exh status type

#223 名前とサムネIDをonsite展示に追加

---

package.json
src/apis/guests/_id@string/check-out/index.ts
src/apis/guests/_id@string/enter/index.ts
src/apis/guests/_id@string/exit/index.ts

#257 GUEST_NOT_FOUND の代わりに 404 を返却

---

package.json
src/apis/log/@types.ts
src/apis/log/index.ts

#236 ログ検索クエリから予約 ID を削除

---

package.json
src/apis/exhibitions/@types.ts
src/apis/guests/_id@string/enter/index.ts

#239 limit -> capacity

---

package.json
src/apis/guests/_id@string/enter/index.ts
src/apis/guests/_id@string/exit/index.ts

Exhibitionを指定させるように

---

src/apis/guests/_id@string/check-out/index.ts
src/apis/guests/_id@string/enter/index.ts
src/apis/guests/_id@string/exit/index.ts
src/apis/guests/check-in/index.ts
src/apis/reservations/_id@string/check/index.ts

close #247
HTTP Status Code と紛らわしいため

#247 status_code を error_code に変更

---

package.json
src/apis/reservations/@types.ts
src/apis/reservations/_id@string/check/index.ts

close #254
`/rsv/_id/check` -> `/guests/check-in` -> `/rsv/_id/check` -> `/guests/check-in` のイメージ

#254 複数人予約に対応

---

package.json
src/apis/guests/check-in/index.ts

#257 check in のエラーコードをしっくりくるように [v3.0.0-alpha.18]

---

package.json
src/apis/exhibitions/_id@string/index.ts
src/apis/exhibitions/index.ts

#264 展示滞在状況の reqHeaders を外す

---

README.md
package.json

#266 update README

---

package.json
src/apis/reservations/_id@string/check/index.ts

#274 [v3.2.0] /reservations/_id/check の認証を外す

---

src/apis/auth/users/_id@string/change_password/index.ts
src/apis/auth/users/_id@string/index.ts
src/apis/auth/users/_id@string/regenerate/index.ts
src/apis/exhibitions/_id@string/index.ts
src/apis/guests/_id@string/check-out/index.ts
src/apis/guests/_id@string/enter/index.ts
src/apis/guests/_id@string/exit/index.ts
src/apis/images/_id@string/index.ts
src/apis/reservations/_id@string/check/index.ts
src/apis/reservations/_id@string/index.ts

なんかerror_code を back で返すの自体は物凄く楽だから "VALIDATION_ERROR" とかも追加してあげてもいいのかなとか思いました。

#276 404 の時のエラーコードを定義

---

package.json

release v3.3.0-alpha.1

---

src/apis/guests/check-in/index.ts
src/apis/reservations/_id@string/check/index.ts

#279 INVALID_RESERVATION_INFO を削除

---

package.json
src/apis/guests/@types.ts
src/apis/guests/check-in/index.ts
src/apis/guests/register-spare/index.ts
src/apis/log/@types.ts

#204 /guest/register-spare を追加

---

package.json
src/apis/guests/_id@string/check-out/index.ts
src/apis/guests/_id@string/enter/index.ts
src/apis/guests/_id@string/exit/index.ts
src/apis/reservations/_id@string/check/index.ts

#283 エラーコードを CHECKED_IN, CHECKED_OUT に統一

---

src/apis/guests/_id@string/check-out/index.ts
src/apis/terms/@types.ts

- feat: Guest Class
- feat: NO_PERMISSION_TO_CHECKOUT

#285 生徒がチェックアウトできないようにする

---

package.json
src/apis/reservations/_id@string/check/index.ts

fix: #291
- fix: use ALL_MEMBER_CHECKED_IN
- v3.3.0-alpha.6

#291 ALL_MEMBER_CHECKED_IN を使う
